
- name: Creating system account kafkaui
  user:
    name: kafkaui
    groups: hadoop
    state: present
    createhome: yes
  become: true
  when: inventory_hostname in groups['kafka-ui-hosts']

- name: Creating kafkaui directories
  file:
    path: "{{ item }}"
    state: directory
    owner: kafkaui
    group: hadoop
    mode: 0755
  with_items:
    - "{{ kafka_kafkaui_home }}"
    - "{{ kafka_kafkaui_conf_dir }}"
    - "{{ kafka_kafkaui_log_dir }}"
  when: inventory_hostname in groups['kafka-ui-hosts']

- name: Open Ports
  shell: "firewall-cmd --zone=public --add-port={{ item }}/tcp --permanent || true"
  args:
    executable: /bin/bash
  with_items:
    - "{{ kafka_kafkaui_port }}"
  ignore_errors: true
  become: true
  when: inventory_hostname in groups['kafka-ui-hosts']

- name: Reload Firewall
  shell: "firewall-cmd --reload || true"
  args:
    executable: /bin/bash
  become: true
  ignore_errors: true
  when: inventory_hostname in groups['kafka-ui-hosts']

- name: Copying kafkaui Distribution
  copy:
    src: "{{ playbook_dir }}/roles/{{ role_name }}/files/{{ kafka_kafkaui_dist_file }}"
    dest: "{{ kafka_kafkaui_home }}"
  when: inventory_hostname in groups['kafka-ui-hosts']

- name: Copying server properties to kafkaui conf directory
  template:
    src: "{{ playbook_dir }}/roles/{{ role_name }}/templates/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: kafkaui
    group: hadoop
    mode: 0755
  with_items:
    - { src: 'kafka-ui-config.yaml', dest: '{{ kafka_kafkaui_conf_dir }}' }
    - { src: 'start-kafka-ui.sh', dest: '{{ kafka_kafkaui_home }}' }
  when: inventory_hostname in groups['kafka-ui-hosts']


- name: chown kafkaui directories
  file:
    path: "{{ item }}"
    owner: kafkaui
    group: hadoop
    recurse: yes
    mode: 0755
  become: yes
  with_items:
    - "{{ kafka_kafkaui_home }}"
    - "{{ kafka_kafkaui_conf_dir }}"
    - "{{ kafka_kafkaui_log_dir }}"
  when: inventory_hostname in groups['kafka-ui-hosts']


- name: Starting kafkaui server
  shell: "{{ item }}"
  args:
    chdir: "{{ kafka_kafkaui_home }}"
  with_items:
    - "chmod +x start-kafka-ui.sh"
    - "echo -ne '\\n' | ./start-kafka-ui.sh"
  when: inventory_hostname in groups['kafka-ui-hosts']
  become_user: kafkaui
