- name: Stopping kafka
  shell: "{{ item }}"
  args:
    chdir: "{{ kafka_home }}"
    executable: /bin/bash
  become_user: kafka
  with_items:
    - bin/kafka-server-stop
  ignore_errors: true

- name: Sleeping for a while
  shell: "{{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - "sleep 10"

- name: Starting kafka broker
  shell: "export JAVA_HOME={{ kafka_java_home }} && export KAFKA_HEAP_OPTS='{{ kafka_heap_opts }}' && nohup bin/kafka-server-start {{ kafka_server_conf_dir }}/server.properties > /dev/null &"
  args:
    chdir: "{{ kafka_home }}"
  become_user: kafka
