- name: Starting kafka broker
  shell: "export JAVA_HOME={{ kafka_java_home }} && export KAFKA_HEAP_OPTS='{{ kafka_heap_opts }}' && nohup bin/kafka-server-start {{ kafka_server_conf_dir }}/server.properties > /dev/null &"
  args:
    chdir: "{{ kafka_home }}"
  become_user: kafka

- name: Starting kafka schema registry
  shell: "export JAVA_HOME={{ kafka_java_home }} && nohup bin/schema-registry-start {{ kafka_schema_registry_conf_dir }}/schema-registry.properties > /dev/null &"
  args:
    chdir: "{{ kafka_home }}"
  when: inventory_hostname in groups['kafka-schema-registry-hosts']
  become_user: kafka

- name: Starting kafkaui server
  shell: "{{ item }}"
  args:
    chdir: "{{ kafka_kafkaui_home }}"
  with_items:
    - "chmod +x start-kafka-ui.sh"
    - "echo -ne '\\n' | ./start-kafka-ui.sh"
  when: inventory_hostname in groups['kafka-ui-hosts']
  become_user: kafkaui