- name: Stopping kafka
  shell: "{{ item }}"
  args:
    chdir: "{{ kafka_home }}"
    executable: /bin/bash
  become_user: kafka
  with_items:
  - bin/kafka-server-stop
  ignore_errors: true

- name: Stopping schema registry
  shell: "{{ item }}"
  args:
    chdir: "{{ kafka_home }}"
    executable: /bin/bash
  become_user: kafka
  with_items:
  - bin/schema-registry-stop
  when: inventory_hostname in groups['kafka-schema-registry-hosts']
  ignore_errors: true

- name: Stopping kafka ui
  shell: "kill $(cat pid)"
  args:
    chdir: "{{ kafka_kafkaui_home }}"
    executable: /bin/bash
  become_user: kafkaui
  when: inventory_hostname in groups['kafka-ui-hosts']
  ignore_errors: true