- name: Stopping kafka
  shell: "{{ item }}"
  args:
    chdir: "{{ kafka_home }}"
    executable: /bin/bash
  become_user: kafka
  with_items:
  - bin/kafka-server-stop
  ignore_errors: true

- name: Stopping schema registry
  shell: "{{ item }}"
  args:
    chdir: "{{ kafka_home }}"
    executable: /bin/bash
  become_user: kafka
  with_items:
  - bin/schema-registry-stop
  when: inventory_hostname in groups['kafka-schema-registry-hosts']
  ignore_errors: true

- name: Stopping kafka ui
  shell: "kill $(cat pid)"
  args:
    chdir: "{{ kafka_kafkaui_home }}"
    executable: /bin/bash
  become_user: kafkaui
  when: inventory_hostname in groups['kafka-ui-hosts']
  ignore_errors: true

- name: Sleeping for a while
  shell: "{{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - "sleep 10"

- name: Removing profile and limits conf
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/etc/profile.d/kafka.sh"
  - "/etc/security/limits.d/kafka.conf"
  ignore_errors: true

  
- name: Removing KAFKA directories
  file: 
    path: "{{ item }}"
    state: absent  
  with_items:
  - "{{ kafka_home }}"
  - "{{ kafka_conf_dir }}"
  - "{{ kafka_log_dir }}"
  ignore_errors: true


- name: Removing KAFKA data directories
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ kafka_data_dir.split(',') }}"
  ignore_errors: true


- name: Removing kafka ui directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kafka_kafkaui_home }}"
    - "{{ kafka_kafkaui_conf_dir }}"
    - "{{ kafka_kafkaui_log_dir }}"
  ignore_errors: true


- name: Removing Users
  user:
    name: "{{ item }}"
    state: absent
  become: true
  with_items:
  - "kafka"
  ignore_errors: true

    
  